services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_DB: tasktrackerapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - task-tracker-pgdata:/var/lib/postgresql/data
    networks:
      - task-tracker-appnet

  app:
    image: task-tracker:latest
    container_name: app
    depends_on:
      - pgdb
    ports:
      - "3000:3000"
    networks:
      - task-tracker-appnet
    volumes:
      - ../logs:/logs

volumes:
  task-tracker-pgdata:

networks:
  task-tracker-appnet:
    name: task-tracker-appnet
